export const SEARCH_QUERY_MIN = 2;

export const GENERIC_TO_BRAND_NAME_MAP = {
  Acetaminophen: ["Tylenol", "Feverall", "Panadol"],
  Albuterol: ["Proventil", "Ventolin", "ProAir"],
  Amiodarone: ["Cordarone", "Pacerone", "Nexterone"],
  Amitriptyline: ["Elavil", "Endep", "Vanatrip"],
  Amlodipine: ["Norvasc", "Amvaz", "Katerzia"],
  Amoxicillin: ["Amoxil", "Trimox", "Moxatag"],
  Aripiprazole: ["Abilify", "Aristada", "Abilify Maintena"],
  Atorvastatin: ["Lipitor", "Atorva", "Torvast"],
  Azithromycin: ["Zithromax", "Azasite", "Zmax"],
  Baclofen: ["Lioresal", "Gablofen", "Ozobax"],
  Buprenorphine: ["Subutex", "Belbuca", "Butrans"],
  Captopril: ["Capoten", "Acepril", "Captoril"],
  Carvedilol: ["Coreg", "Carvil", "Carloc"],
  Ceftriaxone: ["Rocephin", "Cefax", "Ceftril"],
  Ciprofloxacin: ["Cipro", "Ciloxan", "Proquin"],
  Clindamycin: ["Cleocin", "Clinda-Derm", "Clindagel"],
  Clopidogrel: ["Plavix", "Clovix", "Grepid"],
  Codeine: ["Codar", "Tylex", "Tylenol with Codeine"],
  Cyclobenzaprine: ["Flexeril", "Amrix", "Fexmid"],
  Dexamethasone: ["Decadron", "Hexadrol", "DexPak"],
  Diazepam: ["Valium", "Diastat", "Diazemuls"],
  Diclofenac: ["Voltaren", "Cataflam", "Zorvolex"],
  Digoxin: ["Lanoxin", "Digitek", "Cardoxin"],
  Diltiazem: ["Cardizem", "Tiazac", "Dilacor"],
  Diphenhydramine: ["Benadryl", "Nytol", "Sominex"],
  Doxycycline: ["Vibramycin", "Oracea", "Doryx"],
  Duloxetine: ["Cymbalta", "Drizalma", "Irenka"],
  Enalapril: ["Vasotec", "Epaned", "Enalagamma"],
  Enoxaparin: ["Lovenox", "Clexane", "Xaparin"],
  Escitalopram: ["Lexapro", "Cipralex", "Esipram"],
  Esomeprazole: ["Nexium", "Esotrax", "Esomezol"],
  Ethinylestradiol: ["Estinyl", "Feminone", "Lynoral"],
  Famotidine: ["Pepcid", "Acid Controller", "Heartburn Relief"],
  Fentanyl: ["Duragesic", "Actiq", "Fentora"],
  Fluconazole: ["Diflucan", "Trican", "Flucoral"],
  Fluoxetine: ["Prozac", "Sarafem", "Selfemra"],
  Fluticasone: ["Flonase", "Flovent", "Cutivate"],
  Furosemide: ["Lasix", "Frumex", "Diural"],
  Gabapentin: ["Neurontin", "Gralise", "Gabarone"],
  Hydrochlorothiazide: ["HydroDiuril", "Microzide", "Oretic"],
  Hydrocodone: ["Vicodin", "Lortab", "Norco"],
  Ibuprofen: ["Advil", "Motrin", "Nurofen"],
  Imipramine: ["Tofranil", "Imiprex", "Depsonil"],
  "Insulin Glargine": ["Lantus", "Basaglar", "Toujeo"],
  Ipratropium: ["Atrovent", "Ipraxa", "Rinatec"],
  Irbesartan: ["Avapro", "Irovel", "Aprovel"],
  Isosorbide: ["Isordil", "Imdur", "Monoket"],
  Ketorolac: ["Toradol", "Acular", "Ketofen"],
  Lamotrigine: ["Lamictal", "Lamogine", "Lamictin"],
  Lansoprazole: ["Prevacid", "Zoton", "Inhibitol"],
  Levofloxacin: ["Levaquin", "Tavanic", "Elequine"],
  Levothyroxine: ["Synthroid", "Levoxyl", "Euthyrox"],
  Lidocaine: ["Xylocaine", "Lignospan", "Versatis"],
  Lisinopril: ["Prinivil", "Qbrelis", "Zestril\u200b"],
  Loratadine: ["Claritin", "Alavert", "Tavist"],
  Losartan: ["Cozaar", "Losacor", "Repace\u200b "],
  Lovastatin: ["Mevacor", "Altoprev", "Lovalip"],
  Meloxicam: ["Mobic", "Vivlodex", "Qmiiz ODT"],
  Metformin: ["Glucophage", "Fortamet", "Glumetza\u200b "],
  Methotrexate: ["Rheumatrex", "Trexall", "Otrexup"],
  Vecuronium: [
    "Norcuron",
    "Vecuronio",
    "Vecuronio",
    "Bromuro",
    "Vecuronium",
    "Bromide",
  ],
};

export const GENERIC_MEDS_LIST = [
  {
    name: "Acetaminophen",
    count: 100,
    brandMeds: ["Tylenol", "Feverall", "Panadol"],
  },
  {
    name: "Albuterol",
    count: 150,
    brandMeds: ["Proventil", "Ventolin", "ProAir"],
  },
  {
    name: "Amiodarone",
    count: 200,
    brandMeds: ["Cordarone", "Pacerone", "Nexterone"],
  },
  {
    name: "Amitriptyline",
    count: 120,
    brandMeds: ["Elavil", "Endep", "Vanatrip"],
  },
  {
    name: "Amlodipine",
    count: 130,
    brandMeds: ["Norvasc", "Amvaz", "Katerzia"],
  },
  {
    name: "Amoxicillin",
    count: 140,
    brandMeds: ["Amoxil", "Trimox", "Moxatag"],
  },
  {
    name: "Aripiprazole",
    count: 160,
    brandMeds: ["Abilify", "Aristada", "Abilify Maintena"],
  },
  {
    name: "Atorvastatin",
    count: 180,
    brandMeds: ["Lipitor", "Atorva", "Torvast"],
  },
  {
    name: "Azithromycin",
    count: 190,
    brandMeds: ["Zithromax", "Azasite", "Zmax"],
  },
  {
    name: "Baclofen",
    count: 110,
    brandMeds: ["Lioresal", "Gablofen", "Ozobax"],
  },
  {
    name: "Buprenorphine",
    count: 170,
    brandMeds: ["Subutex", "Belbuca", "Butrans"],
  },
  {
    name: "Captopril",
    count: 165,
    brandMeds: ["Capoten", "Acepril", "Captoril"],
  },
  {
    name: "Carvedilol",
    count: 175,
    brandMeds: ["Coreg", "Carvil", "Carloc"],
  },
  {
    name: "Ceftriaxone",
    count: 185,
    brandMeds: ["Rocephin", "Cefax", "Ceftril"],
  },
  {
    name: "Ciprofloxacin",
    count: 195,
    brandMeds: ["Cipro", "Ciloxan", "Proquin"],
  },
  {
    name: "Clindamycin",
    count: 105,
    brandMeds: ["Cleocin", "Clinda-Derm", "Clindagel"],
  },
  {
    name: "Clopidogrel",
    count: 115,
    brandMeds: ["Plavix", "Clovix", "Grepid"],
  },
  {
    name: "Codeine",
    count: 125,
    brandMeds: ["Codar", "Tylex", "Tylenol with Codeine"],
  },
  {
    name: "Cyclobenzaprine",
    count: 135,
    brandMeds: ["Flexeril", "Amrix", "Fexmid"],
  },
  {
    name: "Dexamethasone",
    count: 145,
    brandMeds: ["Decadron", "Hexadrol", "DexPak"],
  },
  {
    name: "Diazepam",
    count: 155,
    brandMeds: ["Valium", "Diastat", "Diazemuls"],
  },
  {
    name: "Diclofenac",
    count: 165,
    brandMeds: ["Voltaren", "Cataflam", "Zorvolex"],
  },
  {
    name: "Digoxin",
    count: 175,
    brandMeds: ["Lanoxin", "Digitek", "Cardoxin"],
  },
  {
    name: "Diltiazem",
    count: 185,
    brandMeds: ["Cardizem", "Tiazac", "Dilacor"],
  },
  {
    name: "Diphenhydramine",
    count: 95,
    brandMeds: ["Benadryl", "Nytol", "Sominex"],
  },
  {
    name: "Doxycycline",
    count: 85,
    brandMeds: ["Vibramycin", "Oracea", "Doryx"],
  },
  {
    name: "Duloxetine",
    count: 75,
    brandMeds: ["Cymbalta", "Drizalma", "Irenka"],
  },
  {
    name: "Enalapril",
    count: 65,
    brandMeds: ["Vasotec", "Epaned", "Enalagamma"],
  },
  {
    name: "Enoxaparin",
    count: 55,
    brandMeds: ["Lovenox", "Clexane", "Xaparin"],
  },
  {
    name: "Escitalopram",
    count: 45,
    brandMeds: ["Lexapro", "Cipralex", "Esipram"],
  },
  {
    name: "Esomeprazole",
    count: 35,
    brandMeds: ["Nexium", "Esotrax", "Esomezol"],
  },
  {
    name: "Ethinylestradiol",
    count: 25,
    brandMeds: ["Estinyl", "Feminone", "Lynoral"],
  },
  {
    name: "Famotidine",
    count: 15,
    brandMeds: ["Pepcid", "Acid Controller", "Heartburn Relief"],
  },
  {
    name: "Fentanyl",
    count: 5,
    brandMeds: ["Duragesic", "Actiq", "Fentora"],
  },
  {
    name: "Fluconazole",
    count: 95,
    brandMeds: ["Diflucan", "Trican", "Flucoral"],
  },
  {
    name: "Fluoxetine",
    count: 85,
    brandMeds: ["Prozac", "Sarafem", "Selfemra"],
  },
  {
    name: "Fluticasone",
    count: 75,
    brandMeds: ["Flonase", "Flovent", "Cutivate"],
  },
  {
    name: "Furosemide",
    count: 65,
    brandMeds: ["Lasix", "Frumex", "Diural"],
  },
  {
    name: "Gabapentin",
    count: 55,
    brandMeds: ["Neurontin", "Gralise", "Gabarone"],
  },
  {
    name: "Hydrochlorothiazide",
    count: 45,
    brandMeds: ["HydroDiuril", "Microzide", "Oretic"],
  },
  {
    name: "Hydrocodone",
    count: 35,
    brandMeds: ["Vicodin", "Lortab", "Norco"],
  },
  {
    name: "Ibuprofen",
    count: 25,
    brandMeds: ["Advil", "Motrin", "Nurofen"],
  },
  {
    name: "Imipramine",
    count: 15,
    brandMeds: ["Tofranil", "Imiprex", "Depsonil"],
  },
  {
    name: "Insulin Glargine",
    count: 5,
    brandMeds: ["Lantus", "Basaglar", "Toujeo"],
  },
  {
    name: "Ipratropium",
    count: 15,
    brandMeds: ["Atrovent", "Ipraxa", "Rinatec"],
  },
  {
    name: "Irbesartan",
    count: 25,
    brandMeds: ["Avapro", "Irovel", "Aprovel"],
  },
  {
    name: "Isosorbide",
    count: 35,
    brandMeds: ["Isordil", "Imdur", "Monoket"],
  },
  {
    name: "Ketorolac",
    count: 45,
    brandMeds: ["Toradol", "Acular", "Ketofen"],
  },
  {
    name: "Lamotrigine",
    count: 55,
    brandMeds: ["Lamictal", "Lamogine", "Lamictin"],
  },
  {
    name: "Lansoprazole",
    count: 65,
    brandMeds: ["Prevacid", "Zoton", "Inhibitol"],
  },
  {
    name: "Levofloxacin",
    count: 75,
    brandMeds: ["Levaquin", "Tavanic", "Elequine"],
  },
  {
    name: "Levothyroxine",
    count: 85,
    brandMeds: ["Synthroid", "Levoxyl", "Euthyrox"],
  },
  {
    name: "Lidocaine",
    count: 95,
    brandMeds: ["Xylocaine", "Lignospan", "Versatis"],
  },
  {
    name: "Lisinopril",
    count: 105,
    brandMeds: ["Prinivil", "Qbrelis", "Zestril​"],
  },
  {
    name: "Loratadine",
    count: 115,
    brandMeds: ["Claritin", "Alavert", "Tavist"],
  },
  {
    name: "Losartan",
    count: 125,
    brandMeds: ["Cozaar", "Losacor", "Repace​ "],
  },
  {
    name: "Lovastatin",
    count: 135,
    brandMeds: ["Mevacor", "Altoprev", "Lovalip"],
  },
  {
    name: "Meloxicam",
    count: 145,
    brandMeds: ["Mobic", "Vivlodex", "Qmiiz ODT"],
  },
  {
    name: "Metformin",
    count: 155,
    brandMeds: ["Glucophage", "Fortamet", "Glumetza​ "],
  },
  {
    name: "Methotrexate",
    count: 165,
    brandMeds: ["Rheumatrex", "Trexall", "Otrexup"],
  },
  {
    name: "Vecuronium",
    count: 175,
    brandMeds: [
      "Norcuron",
      "Vecuronio",
      "Vecuronio",
      "Bromuro",
      "Vecuronium",
      "Bromide",
    ],
  },
];

export const BRAND_MEDS_LIST = [
  "Abilify",
  "Abilify Maintena",
  "Acepril",
  "Acid Controller",
  "Actiq",
  "Acular",
  "Advil",
  "Alavert",
  "Altoprev",
  "Amoxil",
  "Amrix",
  "Amvaz",
  "Aprovel",
  "Aristada",
  "Atorva",
  "Atrovent",
  "Avapro",
  "Azasite",
  "Basaglar",
  "Belbuca",
  "Benadryl",
  "Butrans",
  "Capoten",
  "Captoril",
  "Cardizem",
  "Cardoxin",
  "Carloc",
  "Carvil",
  "Cataflam",
  "Cefax",
  "Ceftril",
  "Ciloxan",
  "Cipralex",
  "Cipro",
  "Claritin",
  "Cleocin",
  "Clexane",
  "Clinda-Derm",
  "Clindagel",
  "Clovix",
  "Codar",
  "Cordarone",
  "Coreg",
  "Cozaar",
  "Cutivate",
  "Cymbalta",
  "Decadron",
  "Depsonil",
  "DexPak",
  "Diastat",
  "Diazemuls",
  "Diflucan",
  "Digitek",
  "Dilacor",
  "Diural",
  "Doryx",
  "Drizalma",
  "Duragesic",
  "Elavil",
  "Elequine",
  "Enalagamma",
  "Endep",
  "Epaned",
  "Esipram",
  "Esomezol",
  "Esotrax",
  "Estinyl",
  "Euthyrox",
  "Feminone",
  "Fentora",
  "Feverall",
  "Fexmid",
  "Flexeril",
  "Flonase",
  "Flovent",
  "Flucoral",
  "Fortamet",
  "Frumex",
  "Gabarone",
  "Gablofen",
  "Glucophage",
  "Glumetza\u200b ",
  "Gralise",
  "Grepid",
  "Heartburn Relief",
  "Hexadrol",
  "HydroDiuril",
  "Imdur",
  "Imiprex",
  "Inhibitol",
  "Ipraxa",
  "Irenka",
  "Irovel",
  "Isordil",
  "Katerzia",
  "Ketofen",
  "Lamictal",
  "Lamictin",
  "Lamogine",
  "Lanoxin",
  "Lantus",
  "Lasix",
  "Levaquin",
  "Levoxyl",
  "Lexapro",
  "Lignospan",
  "Lioresal",
  "Lipitor",
  "Lortab",
  "Losacor",
  "Lovalip",
  "Lovenox",
  "Lynoral",
  "Mevacor",
  "Microzide",
  "Mobic",
  "Monoket",
  "Motrin",
  "Moxatag",
  "Neurontin",
  "Nexium",
  "Nexterone",
  "Norco",
  "Norvasc",
  "Nurofen",
  "Nytol",
  "Oracea",
  "Oretic",
  "Otrexup",
  "Ozobax",
  "Pacerone",
  "Panadol",
  "Pepcid",
  "Plavix",
  "Prevacid",
  "Prinivil",
  "ProAir",
  "Proquin",
  "Proventil",
  "Prozac",
  "Qbrelis",
  "Qmiiz ODT",
  "Repace\u200b ",
  "Rheumatrex",
  "Rinatec",
  "Rocephin",
  "Sarafem",
  "Selfemra",
  "Sominex",
  "Subutex",
  "Synthroid",
  "Tavanic",
  "Tavist",
  "Tiazac",
  "Tofranil",
  "Toradol",
  "Torvast",
  "Toujeo",
  "Trexall",
  "Trican",
  "Trimox",
  "Tylenol",
  "Tylenol with Codeine",
  "Tylex",
  "Valium",
  "Vanatrip",
  "Vasotec",
  "Ventolin",
  "Versatis",
  "Vibramycin",
  "Vicodin",
  "Vivlodex",
  "Voltaren",
  "Xaparin",
  "Xylocaine",
  "Zestril\u200b",
  "Zithromax",
  "Zmax",
  "Zorvolex",
  "Zoton",
  "Norcuron",
  "Vecuronio",
  "Vecuronio",
  "Bromuro",
  "Vecuronium",
  "Bromide",
  "Versed",
  "Dormicum",
  "Hypnovel",
];
